# Copyright (c) 2016-2019 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Ledgerium Documents
site_description: Documentations for Ledgerium Blockchain
site_author: Rahul Golash
site_url: https://github.com/ledgerium-io/ledgeriumdocs/

# Repository
repo_name: ledgerium-io/ledgeriumdocs
repo_url: https://github.com/ledgerium-io/ledgeriumdocs/
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 The Block Ledger Pty Ltd'

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Arial
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: globe
      link: https://www.ledgerium.io/
    - type: github-alt
      link: https://github.com/ledgerium-io
    - type: twitter
      link: https://twitter.com/ledgerium
    - type: linkedin
      link: https://www.linkedin.com/company/blockledger

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  # - Getting Started:
  - Overview: Quorum/Getting Started/Getting Started Overview.md
  - Installing: Quorum/Getting Started/Installing.md
  # - Quorum Examples:
  - Overview: Quorum/Getting Started/Quorum-Examples.md
  - 7nodes Set Up: Quorum/Getting Started/7Nodes-Setup.md
  - 7nodes Example: Quorum/Getting Started/7Nodes.md
  - Creating a Network From Scratch: Quorum/Getting Started/Creating-A-Network-From-Scratch.md
  - Running Quorum: Quorum/Getting Started/running.md
  - Quorum API: Quorum/Getting Started/api.md
  # - Consensus:
  - Consensus: Quorum/Consensus/Consensus.md
  - Istanbul: Quorum/Consensus/istanbul-rpc-api.md
  - Transaction Processing: Quorum/Transaction Processing/Transaction Processing.md
  # - Security Framework:
  - Overview: Quorum/Security/Framework/Overview.md
  # - Quorum Network:
  - Consortium: Quorum/Security/Framework/Quorum Network Security/Consortium.md
  # - Quorum Node:
  - Overview: Quorum/Security/Framework/Quorum Network Security/Node.md
  # - Permissioning:
  - Network Permissioning: Quorum/Security/Framework/Quorum Network Security/Nodes/Permissioning/Network Permissioning.md
  - Transaction Manager: Quorum/Security/Framework/Quorum Network Security/Transaction Manager.md
  - Operational Considerations: Quorum/Security/Framework/Quorum Network Security/Opertional Considerations.md
        # - Decentralized App:
  - Frontend: Quorum/Security/Framework/Decentralized Application/Frontend Components.md
  - Smart Contracts:  Quorum/Security/Framework/Decentralized Application/Smart Contracts Security.md
  # - Privacy:
      # - Tessera:
  - What is Tessera: Quorum/Privacy/Tessera/Tessera.md
  - How Tessera works: Quorum/Privacy/Tessera/How Tessera Works.md
  # - Configuration:
  - Overview: Quorum/Privacy/Tessera/Configuration/Configuration Overview.md
  - Keys Config: Quorum/Privacy/Tessera/Configuration/Keys.md
  - TLS Config: Quorum/Privacy/Tessera/Configuration/TLS.md
  - Using CLI to override config: Quorum/Privacy/Tessera/Configuration/Using CLI to override config.md
  - Sample Configuration: Quorum/Privacy/Tessera/Configuration/Sample Configuration.md
          # - Tessera Services:
  - Transaction Manager: Quorum/Privacy/Tessera/Tessera Services/Transaction Manager.md
  - Enclave: Quorum/Privacy/Tessera/Tessera Services/Enclave.md
              # - Keys:
  - Key Generation: Quorum/Privacy/Tessera/Tessera Services/Keys/Keys.md
  - Setting up Azure Key Vault: Quorum/Privacy/Tessera/Tessera Services/Keys/Setting up an Azure Key Vault.md
  - Setting up Hashicorp Vault: Quorum/Privacy/Tessera/Tessera Services/Keys/Setting up a Hashicorp Vault.md
          # - Usage:
  - Interfaces & API: Quorum/Privacy/Tessera/Usage/Interface & API.md
  - Admin Usage: Quorum/Privacy/Tessera/Usage/Admin Usage.md
  - Monitoring: Quorum/Privacy/Tessera/Usage/Monitoring.md
  - Migration from Constellation: Quorum/Privacy/Tessera/Migration from Constellation.md
  - Product Roadmap: Quorum/roadmap.md
  - FAQ: Quorum/FAQ.md

  - TEST : Quorum/test.md

  - What is Ledgerium: Ledgerium/What_is_Ledgerium.md
  - Ledgerium Foundation: Ledgerium/The_Ledgerium_Foundation.md
  - Community: Ledgerium/Community.md
  - Latest Release: Ledgerium/The_Ledgerium_Latest_Release.md
  - Decentralized Apps: Ledgerium/Web_3_A_platform_for_decentralized_apps.md
  - Accessing Contracts and Transactions: Ledgerium/Accessing_Contracts_and_Transactions.md
  - Account Management: Ledgerium/Account_Management.md
  - Account Types, Gas, and Transactions: Ledgerium/Account_Types,_Gas,_and_Transactions.md
  - Backup and restore accounts: Ledgerium/Backup_and_restore_accounts.md
  - Connecting as a client: Ledgerium/Connecting_as_a_client.md
  - Connecting to Ledgerium Core: Ledgerium/Connecting_to_Ledgerium_Core.md
  - Connecting to Ledgerium TestNet: Ledgerium/Connecting_to_Ledgerium_TestNet.md
  - Connecting to the Network: Ledgerium/Connecting_to_the_Network.md
  - Consensus (Istanbul IFBT): Ledgerium/Consensus_(Istanbul_IFBT).md
  - Consensus Mecahnism (IBFT): Ledgerium/Consensus_Mecahnism_(IBFT).md
  - Console: Ledgerium/Console.md
  - Contracts: Ledgerium/Contracts.md
  - Creating an account: Ledgerium/Creating_an_account.md
  - Creating public transactions contracts: Ledgerium/Creating_public_transactions_contracts.md
  - DAO: Ledgerium/DAO.md
  - Deploying smart contracts: Ledgerium/Deploying_smart_contracts.md
  - Design: Ledgerium/Design.md
  - EVM: Ledgerium/EVM.md
  - FullNode vs Light Node: Ledgerium/Full_Node_vs_Light_Node.md
  - Gas and XLG: Ledgerium/Gas_and_XLG.md
  - GoLang: Ledgerium/GoLang.md
  - Governance_UI: Ledgerium/Governance_UI.md
  - Higher performance: Ledgerium/Higher_performance.md
  - How to get XLG: Ledgerium/How_to_get_XLG.md
  - Importing an unencrypted private_key: Ledgerium/Importing_an_unencrypted_private_key.md
  - Installing LedgeriumCore: Ledgerium/Installing_LedgeriumCore.md
  - Istanbul RPC API: Ledgerium/Istanbul_RPC_API.md
  - Keyfiles: Ledgerium/Keyfiles.md
  - Ledgerium Application: Ledgerium/Ledgerium_Application.md
  - Ledgerium Block Explorer: Ledgerium/Ledgerium_Block_Explorer.md
  - Ledgerium Core: Ledgerium/Ledgerium_Core.md
  - Ledgerium Faucet: Ledgerium/Ledgerium_Faucet.md
  - Ledgerium Test Suite: Ledgerium/Ledgerium_Test_Suite.md
  - Ledgerium Tools: Ledgerium/Ledgerium_Tools.md
  - Ledgerium Wallet: Ledgerium/Ledgerium_Wallet.md
  - Ledgerium: Ledgerium/Ledgerium.md
  - LedgeriumWeb3: Ledgerium/LedgeriumWeb3.md
  - LedgeriumWeb3js: Ledgerium/LedgeriumWeb3js.md
  - Manual backup restore: Ledgerium/Manual_backup_restore.md
  - Modified privacy API: Ledgerium/Modified_privacy_API.md
  - NodeJS: Ledgerium/NodeJS.md
  - Peer Permissioning Governance: Ledgerium/Peer_Permissioning_Governance.md
  - Prerequisites: Ledgerium/Prerequisites.md
  - Privacy Transparency: Ledgerium/Privacy___Transparency.md
  - Questions: Ledgerium/Questions.md
  - Quorum contract design considerations: Ledgerium/Quorum_contract_design_considerations.md
  - Quorum: Ledgerium/Quorum.md
  - RPC: Ledgerium/RPC.md
  - Running a Ledgerium Node: Ledgerium/Running_a_Ledgerium_Node.md
  - Running a validator Node: Ledgerium/Running_a_validator_Node.md
  - Sending XLG: Ledgerium/Sending_XLG.md
  - Setting up a local private testnet: Ledgerium/Setting_up_a_local_private_testnet.md
  - Smart Contracts: Ledgerium/Smart_Contracts.md
  - Solidity: Ledgerium/Solidity.md
  - Test Networks: Ledgerium/Test_Networks.md
  - The Ledgerium network: Ledgerium/The_Ledgerium_network.md
  - Update an account: Ledgerium/Update_an_account.md
  - Using Ledgerium account new: Ledgerium/Using_Ledgerium_account_new.md
  - Using Ledgerium console: Ledgerium/Using_Ledgerium_console.md
  - Using Ledgerium: Ledgerium/Using_Ledgerium.md
  - Viewing Contracts and Transactions: Ledgerium/Viewing_Contracts_and_Transactions.md
  - Wallets: Ledgerium/Wallets.md
  - What is XLG: Ledgerium/What_is_XLG.md
  - Words: Ledgerium/Words.md
  - XLG Reward: Ledgerium/XLG_Reward.md
  - XLG Supply: Ledgerium/XLG_supply.md
  - XLG: Ledgerium/XLG.md
  - z: Ledgerium/z.md
  - Introduction Background: Ledgerium/Introduction_Background.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
